parameters:
    slack_token: '%env(SLACK_TOKEN)%'
    slack_bot_name: '@@slack'
    slack_channel: '#log-factory-manager-api'

monolog:
    channels: ['log-factory-manager-api']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        # Critical errors only
        slack_errors:
            type: slack
            token: '%slack_token%'
            channel: '%slack_channel%'
            bot_name: '%slack_bot_name%'
            icon_emoji: ':ghost:'
            level: critical
            include_extra: true

        # Application's messages
        slack:
            type: slack
            token: '%slack_token%'
            channel: '%slack_channel%'
            bot_name: '%slack_bot_name%'
            icon_emoji: ":heavy_check_mark:"
            level: debug
            include_extra: true
            channels: [ 'log-factory-manager-api' ]
